#!/bin/bash

# Auto-generated cleanup script
# Remove unused images from /client/public

rm "/home/runner/workspace/client/public/apple-touch-icon.svg"
rm "/home/runner/workspace/client/public/favicon-16x16.svg"
rm "/home/runner/workspace/client/public/favicon-32x32.svg"
rm "/home/runner/workspace/client/public/images/blog/image-1750178585894-438339842.png"
rm "/home/runner/workspace/client/public/images/blog/workflow-automation-hero.jpg"
rm "/home/runner/workspace/client/public/og-image-background.jpg"
rm "/home/runner/workspace/client/public/og-image-clean-final.jpg"
rm "/home/runner/workspace/client/public/og-image-clean-logo-only.jpg"
rm "/home/runner/workspace/client/public/og-image-clean.jpg"
rm "/home/runner/workspace/client/public/og-image-complete.jpg"
rm "/home/runner/workspace/client/public/og-image-complete.svg"
rm "/home/runner/workspace/client/public/og-image-corrected.jpg"
rm "/home/runner/workspace/client/public/og-image-final-clean.jpg"
rm "/home/runner/workspace/client/public/og-image-final-clean.svg"
rm "/home/runner/workspace/client/public/og-image-final-fixed.jpg"
rm "/home/runner/workspace/client/public/og-image-final.svg"
rm "/home/runner/workspace/client/public/og-image-fixed.jpg"
rm "/home/runner/workspace/client/public/og-image-fixed.svg"
rm "/home/runner/workspace/client/public/og-image-logo-only.jpg"
rm "/home/runner/workspace/client/public/og-image-new.svg"
rm "/home/runner/workspace/client/public/og-image-perfect.jpg"
rm "/home/runner/workspace/client/public/og-image-proper.jpg"
rm "/home/runner/workspace/client/public/og-image-text-and-logo.jpg"
rm "/home/runner/workspace/client/public/og-image-text-only.jpg"
rm "/home/runner/workspace/client/public/og-image-updated.jpg"
rm "/home/runner/workspace/client/public/og-image-with-logo.jpg"
rm "/home/runner/workspace/client/public/og-image-with-text-final.jpg"
rm "/home/runner/workspace/client/public/og-image-with-text.jpg"
rm "/home/runner/workspace/client/public/og-image.jpg"
rm "/home/runner/workspace/client/public/og-image.svg"
rm "/home/runner/workspace/client/public/swim-logo-original.png"
rm "/home/runner/workspace/client/public/swim-logo-proper.png"
rm "/home/runner/workspace/client/public/temp_bg.jpg"

echo "Cleanup completed. Removed 33 unused images."